### ISSUE TITLE
Why does BasicDemo have many errors???

### ISSUE THREAD

**Issue by sourceskyboxer** [AndresTraks/BulletSharp#48]
Hello guys, 

I really want check BasicDemo

But I have got errors.  Because I already installed BulletSharp, OpenTK and SharpDX from Nuget Server and It can't resolve if I have error like concflicts:
BasicDemo.cs:
Matrix4 modelLookAt = body.MotionState.WorldTransform * lookat;
Because it shows error Matrix4 and Matrix

Physic.cs:
World.Gravity = new Vector3(0, -10, 0);
error...

Vector3 localInertia = colShape.CalculateLocalInertia(mass);
Conflict

and more...

How do I fix?

**Comment by AndresTraks** [comment]
You don't have to install Nuget packages manually. All you should have to do is compile BulletSharp.sln in Release mode and then build Demos.sln.

The Nuget package is a different version of BulletSharp: https://github.com/AndresTraks/BulletSharpPInvoke
It is similar, but not compatible with the demos here.

The solutions are a bit badly organized. It's mostly because you couldn't put C++/CLI and C# projects into the same solution in early versions of Visual Studio Express. I'm thinking of ways to improve this.

**Comment by sourceskyboxer** [comment]
Okay I will try thanks! PS: Nice idea OpenTK with BulletSharp = It is really good like Unity 3D. Nice job!
